# Regression Dataset

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

candydata = pd.read_csv("C:/Users/rushi/OneDrive/Desktop/Projects DS,ML,DL,AI/Candy bar prediction-Regression/candy-data.csv")
candydata

competitorname  chocolate  fruity  caramel  peanutyalmondy  \
0                    100 Grand          1       0        1               0   
1                 3 Musketeers          1       0        0               0   
2                     One dime          0       0        0               0   
3                  One quarter          0       0        0               0   
4                    Air Heads          0       1        0               0   
..                         ...        ...     ...      ...             ...   
80                   Twizzlers          0       1        0               0   
81                    Warheads          0       1        0               0   
82        WelchÕs Fruit Snacks          0       1        0               0   
83  WertherÕs Original Caramel          0       0        1               0   
84                    Whoppers          1       0        0               0   

    nougat  crispedricewafer  hard  bar  pluribus  sugarpercent  pricepercent  \
0        0                 1     0    1         0         0.732         0.860   
1        1                 0     0    1         0         0.604         0.511   
2        0                 0     0    0         0         0.011         0.116   
3        0                 0     0    0         0         0.011         0.511   
4        0                 0     0    0         0         0.906         0.511   
..     ...               ...   ...  ...       ...           ...           ...   
80       0                 0     0    0         0         0.220         0.116   
81       0                 0     1    0         0         0.093         0.116   
82       0                 0     0    0         1         0.313         0.313   
83       0                 0     1    0         0         0.186         0.267   
84       0                 1     0    0         1         0.872         0.848   

    winpercent  
0    66.971725  
1    67.602936  
2    32.261086  
3    46.116505  
4    52.341465  
..         ...  
80   45.466282  
81   39.011898  
82   44.375519  
83   41.904308  
84   49.524113  

[85 rows x 13 columns]

In [6]:
x = candydata.iloc[:,[10,12]].values
y = candydata.iloc[:,9].values

In [7]:
x[:10]


array([[7.3199999e-01, 6.6971725e+01],
       [6.0399997e-01, 6.7602936e+01],
       [1.1000000e-02, 3.2261086e+01],
       [1.1000000e-02, 4.6116505e+01],
       [9.0600002e-01, 5.2341465e+01],
       [4.6500000e-01, 5.0347546e+01],
       [6.0399997e-01, 5.6914547e+01],
       [3.1299999e-01, 2.3417824e+01],
       [9.0600002e-01, 3.8010963e+01],
       [6.0399997e-01, 3.4517681e+01]])

In [8]:
y[:10]

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 0], dtype=int64)

In [9]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.20, random_state = 0)

In [10]:
xtrain

array([[9.8799998e-01, 7.2887901e+01],
       [2.6699999e-01, 3.7887188e+01],
       [6.0399997e-01, 4.8982651e+01],
       [1.2700000e-01, 5.5375454e+01],
       [6.0399997e-01, 5.6914547e+01],
       [6.0399997e-01, 7.0735641e+01],
       [6.8999998e-02, 5.9863998e+01],
       [2.2000000e-01, 4.5466282e+01],
       [7.2000003e-01, 8.4180290e+01],
       [5.6900001e-01, 3.4578991e+01],
       [3.1299999e-01, 4.3068897e+01],
       [3.1299999e-01, 4.7173229e+01],
       [1.1000000e-02, 4.6116505e+01],
       [2.2000000e-01, 3.4722000e+01],
       [2.2000000e-01, 3.9446800e+01],
       [1.9700000e-01, 5.7219250e+01],
       [4.6500000e-01, 5.7119740e+01],
       [6.0399997e-01, 5.4861111e+01],
       [8.7199998e-01, 4.9524113e+01],
       [8.6000001e-01, 6.5716286e+01],
       [4.0599999e-01, 7.3434990e+01],
       [9.0600002e-01, 5.2341465e+01],
       [1.2700000e-01, 4.3088924e+01],
       [9.0600002e-01, 4.6783348e+01],
       [3.1299999e-01, 5.4526451e+01],
       [9.6499997e-01, 6.

In [28]:
xtest

array([[28.2, 86.4],
       [29.2, 68.5],
       [28.4, 71.7],
       [27.3, 85. ],
       [28.5, 83.8],
       [26.8, 68.8],
       [31.8, 71.3],
       [31.5, 72.7],
       [28.5, 78.4],
       [25.9, 92.9],
       [29.4, 73. ],
       [29.3, 68.5],
       [30. , 79.7],
       [25.8, 94.8],
       [28. , 40.7],
       [29.4, 68.4],
       [29. , 72.7],
       [29.7, 65.4],
       [29.6, 84.1],
       [29.1, 84.9],
       [31.4, 74.8],
       [25.2, 67.3],
       [29. , 48.9],
       [26.1, 58. ],
       [30.1, 82.6],
       [29. , 85.5],
       [27.9, 86.7],
       [23.9, 65.8],
       [29.7, 78. ],
       [31.3, 73.8],
       [29.7, 76.9],
       [30.7, 65.5],
       [21.7, 35.4],
       [23.3, 91.2],
       [30.4, 75.7],
       [26.9, 90.3],
       [28.6, 81. ],
       [23.6, 58.8],
       [29.3, 69.5],
       [28.5, 82. ],
       [31.2, 60.1],
       [31.2, 70.3],
       [30.8, 40.1],
       [28.6, 56.5],
       [30.9, 72.5],
       [24.3, 63.8],
       [27.1, 46.2],
       [28.8,

In [29]:
len(xtrain)

1424

In [30]:
len(xtest)

357

In [31]:
ytrain

array([  0,   0,   0, ..., 100, 100,   0], dtype=int64)

In [32]:
ytest

array([100, 100,   0, 100, 100,   0, 100,   0, 100, 100,   0, 100, 100,
       100,   0,   0,   0,   0, 100, 100, 100, 100,   0,   0, 100, 100,
       100,   0, 100, 100, 100,   0,   0, 100,   0, 100, 100,   0, 100,
       100,   0,   0,   0,   0, 100,   0,   0, 100, 100,   0, 100,   0,
         0,   0, 100, 100,   0, 100,   0,   0, 100,   0,   0,   0, 100,
       100,   0,   0, 100,   0, 100,   0,   0,   0, 100,   0, 100, 100,
         0,   0, 100, 100, 100, 100, 100,   0,   0, 100,   0, 100, 100,
       100,   0, 100,   0, 100,   0, 100,   0,   0,   0,   0,   0, 100,
         0,   0,   0, 100,   0,   0,   0,   0,   0, 100, 100,   0, 100,
       100, 100, 100,   0,   0, 100, 100, 100, 100,   0, 100,   0, 100,
       100,   0,   0, 100,   0,   0, 100,   0, 100,   0, 100, 100,   0,
         0,   0, 100, 100, 100, 100,   0,   0,   0,   0, 100, 100,   0,
       100,   0,   0, 100,   0, 100, 100, 100, 100,   0,   0, 100, 100,
       100,   0,   0, 100, 100, 100,   0,   0,   0,   0,   0, 10

In [14]:
len(ytrain)

68

In [15]:
len(xtest)

17

In [16]:
from sklearn.preprocessing import StandardScaler
sc_x =StandardScaler()
xtrain = sc_x.fit_transform(xtrain)
xtest = sc_x.transform(xtest)

print(xtrain[0:10])

[[ 1.8799885   1.43317793]
 [-0.788881   -0.94893241]
 [ 0.45856557 -0.1937873 ]
 [-1.30710806  0.2412999 ]
 [ 0.45856557  0.34604889]
 [ 0.45856557  1.28669746]
 [-1.52180215  0.5467853 ]
 [-0.9628572  -0.43310754]
 [ 0.88795396  2.20172561]
 [ 0.32900895 -1.17408468]]


# Logistic Regression Model

In [17]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(xtrain, ytrain)

LogisticRegression(random_state=0)

In [18]:
xtest

array([[-1.73649623, -1.33183877],
       [ 0.93237328, -0.65050171],
       [-0.788881  , -0.39706728],
       [ 1.36176144,  0.23984289],
       [-1.4329632 , -0.96015205],
       [-1.60693945, -0.86359552],
       [ 0.37342827, -0.98559343],
       [-1.13313186, -0.41469992],
       [ 0.93237328, -1.12564273],
       [-0.61860639,  0.99642887],
       [-0.61860639, -1.93370153],
       [-1.4329632 , -1.61317027],
       [ 1.27662413,  1.00350053],
       [ 1.70601226,  0.76601271],
       [ 1.57645564, -0.94050841],
       [ 0.93237328, -0.86057037],
       [-0.18551653,  0.31718878]])

In [19]:
y_pred = classifier.predict(xtest)
y_pred

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0], dtype=int64)

In [20]:
ytest

array([0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0], dtype=int64)

In [21]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest, y_pred)

print("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[2 4]
 [3 8]]


In [22]:
from sklearn.metrics import accuracy_score
print("Accuracy : ",accuracy_score(ytest,y_pred))

Accuracy :  0.5882352941176471


# K-NN model

In [23]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=10, metric='minkowski',p=2)
classifier.fit(xtrain,ytrain)

KNeighborsClassifier(n_neighbors=10)

In [24]:
y_pred = classifier.predict(xtest)
y_pred

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0], dtype=int64)

In [25]:
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(ytest, y_pred)
cm

array([[4, 2],
       [6, 5]], dtype=int64)

In [26]:
from sklearn.metrics import accuracy_score
print("K-NN Accuracy : ",accuracy_score(ytest,y_pred))

K-NN Accuracy :  0.5294117647058824
